[features]
seeds = false
skip-lint = false
[programs.localnet]
type_cosplay = "4kaRTFx13ME6zVRiQxefhBuWZd4NurEn9p6K8SSw9fLQ"
type_checked = "FZLRa6vX64QL6Vj2JkqY1Uzyzjgi2PYjCABcDabMo8U7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
